### ISSUE TITLE
some python 3.2 issues

### ISSUE THREAD

**Issue by beelze** [pwr/Solaar#133]
I have python3 as default python interpreter. In general solaar works well with 3.2 but some minor issues were seen (my logitech devices are: unified receiver, K800 keyboard and performance mx mouse):
1. After solaar start – K800 no shown in tree, only mouse
2. K800 appeared in tree after I turned keyboard off (with hardware switch)

errors in console seems unrelated with this issues (same errors seen with python 2.7), but…

Traceback (most recent call last):
  File "/usr/lib64/python3.2/site-packages/solaar/ui/**init**.py", line 176, in _status_changed
    window.update(device, need_popup)
  File "/usr/lib64/python3.2/site-packages/solaar/ui/window.py", line 780, in update
    _model.set_value(item, _COLUMN.STATUS_ICON, 'network-wireless' if is_pairing else None)
  File "/usr/lib64/python3.2/site-packages/gi/overrides/Gtk.py", line 1237, in set_value
    Gtk.TreeStore.set_value(self, treeiter, column, value)
  File "/usr/lib64/python3.2/site-packages/gi/types.py", line 43, in function
    return info.invoke(_args, *_kwargs)
TypeError: Argument 3 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib64/python3.2/site-packages/solaar/ui/__init__.py", line 176, in _status_changed
    window.update(device, need_popup)
  File "/usr/lib64/python3.2/site-packages/solaar/ui/window.py", line 780, in update
    _model.set_value(item, _COLUMN.STATUS_ICON, 'network-wireless' if is_pairing else None)
  File "/usr/lib64/python3.2/site-packages/gi/overrides/Gtk.py", line 1237, in set_value
    Gtk.TreeStore.set_value(self, treeiter, column, value)
  File "/usr/lib64/python3.2/site-packages/gi/types.py", line 43, in function
    return info.invoke(_args, *_kwargs)
TypeError: Argument 3 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib64/python3.2/site-packages/solaar/ui/__init__.py", line 176, in _status_changed
    window.update(device, need_popup)
  File "/usr/lib64/python3.2/site-packages/solaar/ui/window.py", line 780, in update
    _model.set_value(item, _COLUMN.STATUS_ICON, 'network-wireless' if is_pairing else None)
  File "/usr/lib64/python3.2/site-packages/gi/overrides/Gtk.py", line 1237, in set_value
    Gtk.TreeStore.set_value(self, treeiter, column, value)
  File "/usr/lib64/python3.2/site-packages/gi/types.py", line 43, in function
    return info.invoke(_args, *_kwargs)
TypeError: Argument 3 does not allow None as a value

**Comment by MestreLion** [comment]
Exactly the same problem here, with Python 2.7 under Ubuntu 12.04 64-bit.

It seems harmless as the software works perfectly (it lists all my devices, and I was able to pair an additional mouse), but it's a very annoying traceback. I can see it either when launching the GUI from the terminal, of directly via menu (in the latter, it triggers Ubuntu's apport, errors are the same)

**Comment by jrbenito** [comment]
@MestreLion @beelze 

Still a valid issue?

**Comment by Lekensteyn** [comment]
Should have been fixed by 9a6cdd9cee773b5b315aef81d32f629c48760e5c in the master branch (not 0.9.2), please re-open or comment if that is not the case.
