### ISSUE TITLE
Supported device not supported ? (G700s)

### ISSUE THREAD

**Issue by efolio** [pwr/Solaar#375]
Hi,

Just bought a unifying receiver to plug my G700s mouse.
This mouse is in the device supported list of this repo. 

However, I cannot pair it.
I run the latest Kubuntu (17.04), up-to-date.

```
$ git clone https://github.com/pwr/Solaar.git
Cloning into 'Solaar'...
remote: Counting objects: 6940, done.
remote: Total 6940 (delta 0), reused 0 (delta 0), pack-reused 6940
Receiving objects: 100% (6940/6940), 6.22 MiB | 1.11 MiB/s, done.
Resolving deltas: 100% (3286/3286), done.
```

```
$ cd Solaar
$ sudo ./setup.py build
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/hidapi
copying lib/hidapi/hidconsole.py -> build/lib.linux-x86_64-2.7/hidapi
copying lib/hidapi/__init__.py -> build/lib.linux-x86_64-2.7/hidapi
copying lib/hidapi/udev.py -> build/lib.linux-x86_64-2.7/hidapi
creating build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/i18n.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/settings_templates.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/hidpp20.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/settings.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/base_usb.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/hidpp10.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/listener.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/descriptors.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/__init__.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/receiver.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/common.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/notifications.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/status.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/special_keys.py -> build/lib.linux-x86_64-2.7/logitech_receiver
copying lib/logitech_receiver/base.py -> build/lib.linux-x86_64-2.7/logitech_receiver
creating build/lib.linux-x86_64-2.7/solaar
copying lib/solaar/i18n.py -> build/lib.linux-x86_64-2.7/solaar
copying lib/solaar/listener.py -> build/lib.linux-x86_64-2.7/solaar
copying lib/solaar/configuration.py -> build/lib.linux-x86_64-2.7/solaar
copying lib/solaar/__init__.py -> build/lib.linux-x86_64-2.7/solaar
copying lib/solaar/gtk.py -> build/lib.linux-x86_64-2.7/solaar
copying lib/solaar/async.py -> build/lib.linux-x86_64-2.7/solaar
copying lib/solaar/upower.py -> build/lib.linux-x86_64-2.7/solaar
creating build/lib.linux-x86_64-2.7/solaar/ui
copying lib/solaar/ui/config_panel.py -> build/lib.linux-x86_64-2.7/solaar/ui
copying lib/solaar/ui/about.py -> build/lib.linux-x86_64-2.7/solaar/ui
copying lib/solaar/ui/tray.py -> build/lib.linux-x86_64-2.7/solaar/ui
copying lib/solaar/ui/action.py -> build/lib.linux-x86_64-2.7/solaar/ui
copying lib/solaar/ui/__init__.py -> build/lib.linux-x86_64-2.7/solaar/ui
copying lib/solaar/ui/notify.py -> build/lib.linux-x86_64-2.7/solaar/ui
copying lib/solaar/ui/icons.py -> build/lib.linux-x86_64-2.7/solaar/ui
copying lib/solaar/ui/window.py -> build/lib.linux-x86_64-2.7/solaar/ui
copying lib/solaar/ui/pair_window.py -> build/lib.linux-x86_64-2.7/solaar/ui
creating build/lib.linux-x86_64-2.7/solaar/cli
copying lib/solaar/cli/pair.py -> build/lib.linux-x86_64-2.7/solaar/cli
copying lib/solaar/cli/unpair.py -> build/lib.linux-x86_64-2.7/solaar/cli
copying lib/solaar/cli/__init__.py -> build/lib.linux-x86_64-2.7/solaar/cli
copying lib/solaar/cli/show.py -> build/lib.linux-x86_64-2.7/solaar/cli
copying lib/solaar/cli/config.py -> build/lib.linux-x86_64-2.7/solaar/cli
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/solaar -> build/scripts-2.7
copying and adjusting bin/solaar-cli -> build/scripts-2.7
changing mode of build/scripts-2.7/solaar from 644 to 755
changing mode of build/scripts-2.7/solaar-cli from 644 to 755
```

```
$ sudo ./setup.py install
running install
running build
running build_py
running build_scripts
running install_lib
copying build/lib.linux-x86_64-2.7/logitech_receiver/i18n.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/settings_templates.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/hidpp20.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/settings.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/base_usb.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/hidpp10.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/listener.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/descriptors.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/__init__.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/receiver.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/common.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/notifications.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/status.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/special_keys.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/logitech_receiver/base.py -> /usr/local/lib/python2.7/dist-packages/logitech_receiver
copying build/lib.linux-x86_64-2.7/solaar/i18n.py -> /usr/local/lib/python2.7/dist-packages/solaar
copying build/lib.linux-x86_64-2.7/solaar/cli/pair.py -> /usr/local/lib/python2.7/dist-packages/solaar/cli
copying build/lib.linux-x86_64-2.7/solaar/cli/unpair.py -> /usr/local/lib/python2.7/dist-packages/solaar/cli
copying build/lib.linux-x86_64-2.7/solaar/cli/__init__.py -> /usr/local/lib/python2.7/dist-packages/solaar/cli
copying build/lib.linux-x86_64-2.7/solaar/cli/show.py -> /usr/local/lib/python2.7/dist-packages/solaar/cli
copying build/lib.linux-x86_64-2.7/solaar/cli/config.py -> /usr/local/lib/python2.7/dist-packages/solaar/cli
copying build/lib.linux-x86_64-2.7/solaar/listener.py -> /usr/local/lib/python2.7/dist-packages/solaar
copying build/lib.linux-x86_64-2.7/solaar/ui/config_panel.py -> /usr/local/lib/python2.7/dist-packages/solaar/ui
copying build/lib.linux-x86_64-2.7/solaar/ui/about.py -> /usr/local/lib/python2.7/dist-packages/solaar/ui
copying build/lib.linux-x86_64-2.7/solaar/ui/tray.py -> /usr/local/lib/python2.7/dist-packages/solaar/ui
copying build/lib.linux-x86_64-2.7/solaar/ui/action.py -> /usr/local/lib/python2.7/dist-packages/solaar/ui
copying build/lib.linux-x86_64-2.7/solaar/ui/__init__.py -> /usr/local/lib/python2.7/dist-packages/solaar/ui
copying build/lib.linux-x86_64-2.7/solaar/ui/notify.py -> /usr/local/lib/python2.7/dist-packages/solaar/ui
copying build/lib.linux-x86_64-2.7/solaar/ui/icons.py -> /usr/local/lib/python2.7/dist-packages/solaar/ui
copying build/lib.linux-x86_64-2.7/solaar/ui/window.py -> /usr/local/lib/python2.7/dist-packages/solaar/ui
copying build/lib.linux-x86_64-2.7/solaar/ui/pair_window.py -> /usr/local/lib/python2.7/dist-packages/solaar/ui
copying build/lib.linux-x86_64-2.7/solaar/configuration.py -> /usr/local/lib/python2.7/dist-packages/solaar
copying build/lib.linux-x86_64-2.7/solaar/__init__.py -> /usr/local/lib/python2.7/dist-packages/solaar
copying build/lib.linux-x86_64-2.7/solaar/gtk.py -> /usr/local/lib/python2.7/dist-packages/solaar
copying build/lib.linux-x86_64-2.7/solaar/async.py -> /usr/local/lib/python2.7/dist-packages/solaar
copying build/lib.linux-x86_64-2.7/solaar/upower.py -> /usr/local/lib/python2.7/dist-packages/solaar
copying build/lib.linux-x86_64-2.7/hidapi/hidconsole.py -> /usr/local/lib/python2.7/dist-packages/hidapi
copying build/lib.linux-x86_64-2.7/hidapi/__init__.py -> /usr/local/lib/python2.7/dist-packages/hidapi
copying build/lib.linux-x86_64-2.7/hidapi/udev.py -> /usr/local/lib/python2.7/dist-packages/hidapi
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/i18n.py to i18n.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/settings_templates.py to settings_templates.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/hidpp20.py to hidpp20.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/settings.py to settings.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/base_usb.py to base_usb.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/hidpp10.py to hidpp10.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/listener.py to listener.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/descriptors.py to descriptors.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py to receiver.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/common.py to common.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/notifications.py to notifications.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/status.py to status.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/special_keys.py to special_keys.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/logitech_receiver/base.py to base.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/i18n.py to i18n.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/cli/pair.py to pair.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/cli/unpair.py to unpair.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/cli/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/cli/show.py to show.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/cli/config.py to config.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/listener.py to listener.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/ui/config_panel.py to config_panel.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/ui/about.py to about.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/ui/tray.py to tray.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/ui/action.py to action.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/ui/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/ui/notify.py to notify.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/ui/icons.py to icons.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/ui/window.py to window.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/ui/pair_window.py to pair_window.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/configuration.py to configuration.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/gtk.py to gtk.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/async.py to async.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/solaar/upower.py to upower.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/hidapi/hidconsole.py to hidconsole.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/hidapi/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/hidapi/udev.py to udev.pyc
running install_scripts
copying build/scripts-2.7/solaar -> /usr/local/bin
copying build/scripts-2.7/solaar-cli -> /usr/local/bin
changing mode of /usr/local/bin/solaar to 755
changing mode of /usr/local/bin/solaar-cli to 755
running install_data
copying share/solaar/icons/solaar-attention.svg -> /usr/local/share/solaar/icons
copying share/solaar/icons/solaar.svg -> /usr/local/share/solaar/icons
copying share/solaar/icons/solaar-init.svg -> /usr/local/share/solaar/icons
copying share/solaar/icons/light_100.png -> /usr/local/share/solaar/icons
copying share/solaar/icons/light_040.png -> /usr/local/share/solaar/icons
copying share/solaar/icons/light_080.png -> /usr/local/share/solaar/icons
copying share/solaar/icons/light_060.png -> /usr/local/share/solaar/icons
copying share/solaar/icons/light_000.png -> /usr/local/share/solaar/icons
copying share/solaar/icons/light_unknown.png -> /usr/local/share/solaar/icons
copying share/solaar/icons/light_020.png -> /usr/local/share/solaar/icons
copying share/solaar/icons/solaar.svg -> /usr/local/share/icons/hicolor/scalable/apps
copying share/applications/solaar.desktop -> /usr/local/share/applications
copying share/applications/solaar.desktop -> /etc/xdg/autostart
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/solaar-0.9.2.egg-info
Writing /usr/local/lib/python2.7/dist-packages/solaar-0.9.2.egg-info
```

```
$ solaar -V
solaar 0.9.2
```

```
$ solaar show
Unifying Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c52b
  Serial       : C00E9526
    Firmware   : 12.03.B0025
    Bootloader : 02.15
    Other      : AA.AA
  Has 0 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)
```

```
$ solaar pair
Pairing: turn your new device on (timing out in 20 seconds).
solaar: error: pairing failed: device not supported
```

```
$ solaar -d pair
10:45:00,783    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 1 of <UnifyingReceiver(/dev/hidraw3,
3)>
10:45:00,783    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 413, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 1, 'receiver': <UnifyingReceiver(/dev/hidraw3,3)>}
10:45:00,783  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw3,3)>: looked for device 1, not found
10:45:00,789    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 2 of <UnifyingReceiver(/dev/hidraw3,
3)>
10:45:00,789    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 413, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 2, 'receiver': <UnifyingReceiver(/dev/hidraw3,3)>}
10:45:00,789  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw3,3)>: looked for device 2, not found
10:45:00,793    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 3 of <UnifyingReceiver(/dev/hidraw3,
3)>
10:45:00,793    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 413, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 3, 'receiver': <UnifyingReceiver(/dev/hidraw3,3)>}
10:45:00,793  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw3,3)>: looked for device 3, not found
10:45:00,797    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 4 of <UnifyingReceiver(/dev/hidraw3,3)>
10:45:00,797    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 413, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 4, 'receiver': <UnifyingReceiver(/dev/hidraw3,3)>}
10:45:00,797  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw3,3)>: looked for device 4, not found
10:45:00,801    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 5 of <UnifyingReceiver(/dev/hidraw3,3)>
10:45:00,801    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 413, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 5, 'receiver': <UnifyingReceiver(/dev/hidraw3,3)>}
10:45:00,801  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw3,3)>: looked for device 5, not found
10:45:00,805    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 6 of <UnifyingReceiver(/dev/hidraw3,3)>
10:45:00,805    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 413, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/local/lib/python2.7/dist-packages/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 6, 'receiver': <UnifyingReceiver(/dev/hidraw3,3)>}
10:45:00,805  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw3,3)>: looked for device 6, not found
10:45:00,809     INFO [MainThread] logitech_receiver.notifications: <UnifyingReceiver(/dev/hidraw3,3)>: pairing lock is open
Pairing: turn your new device on (timing out in 20 seconds).
10:45:05,653     INFO [MainThread] logitech_receiver.notifications: <UnifyingReceiver(/dev/hidraw3,3)>: pairing lock is closed
10:45:05,653  WARNING [MainThread] logitech_receiver.notifications: pairing error 2: device not supported
solaar: error: pairing failed: device not supported
```

I tried ltunify, same issue…
```
$ ./ltunify -D pair

wr: 10 ff 81 00 00 00 00
rd: 10 ff 81 00 00 09 00
Reporting Flags (Receiver) = 09
Wireless notifications     = yes
Software Present           = no
wr: 10 ff 80 b2 01 00 1e
rd: 10 ff 4a 01 00 00 00
Receiver lock state is now open
Expected short msg 0x80, got short msg 0x4a
rd: 10 ff 80 b2 00 00 00
Please turn your wireless device off and on to start pairing.
rd: 10 ff 4a 00 02 00 00
Pairing result: Failure (2)
wr: 10 ff 80 b2 02 00 00
rd: 10 ff 80 b2 00 00 00

wr: 10 ff 81 00 00 00 00
rd: 10 ff 81 00 00 09 00
Reporting Flags (Receiver) = 09
Wireless notifications     = yes
Software Present           = no
```

Any ideas/help?

**Comment by doctor64** [comment]
Are you sure what G700s (it's a Gaming series mouse, right?) are compatible with unifying receiver? Some reports indicate what Gaming have they own, uncompatible receiver. see #372

**Comment by efolio** [comment]
Seems that way… :/
sigh

You should remove the G-series in the compatible devices though…

Thank you.
