### ISSUE TITLE
Last commit broke solaar's GUI - no configuration options shown for any device

### ISSUE THREAD

**Issue by arigit** [pwr/Solaar#453]
There were a a series of commit done on Aug 11 - the last one of which completely broke the GUI, this one:

https://github.com/pwr/Solaar/commit/867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d
"Merge pull request #146 from tristianc/master  -  Added border around tree view."

This is on Ubuntu 18.04 LTS.

The application runs and the tray icon shows, clicking on it the list of logitech devices shows as usual, and after selecting one, the regular properties window opens, but instead of containing device properties (DPI, battery level etc) it is completely empty except for a label saying "Select a device"  (?)

Running solaar from the command the command line shows a string of error messages that pop up every time the "empty properties window" opens:

> (solaar:3570): Gtk-CRITICAL **: 14:45:35.469: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed
Traceback (most recent call last):
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/__init__.py", line 165, in _status_changed
    window.update(device, need_popup)
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/window.py", line 768, in update
    selected_device_id = _find_selected_device_id()
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/window.py", line 370, in _find_selected_device_id
    model, item = selection.get_selected()
AttributeError: 'NoneType' object has no attribute 'get_selected'
Traceback (most recent call last):
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/__init__.py", line 165, in _status_changed
    window.update(device, need_popup)
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/window.py", line 768, in update
    selected_device_id = _find_selected_device_id()
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/window.py", line 370, in _find_selected_device_id
    model, item = selection.get_selected()
AttributeError: 'NoneType' object has no attribute 'get_selected'
Traceback (most recent call last):
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/__init__.py", line 165, in _status_changed
    window.update(device, need_popup)
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/window.py", line 768, in update
    selected_device_id = _find_selected_device_id()
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/window.py", line 370, in _find_selected_device_id
    model, item = selection.get_selected()
AttributeError: 'NoneType' object has no attribute 'get_selected'
Traceback (most recent call last):
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/__init__.py", line 165, in _status_changed
    window.update(device, need_popup)
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/window.py", line 768, in update
    selected_device_id = _find_selected_device_id()
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/window.py", line 370, in _find_selected_device_id
    model, item = selection.get_selected()
AttributeError: 'NoneType' object has no attribute 'get_selected'
Traceback (most recent call last):
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/__init__.py", line 165, in _status_changed
    window.update(device, need_popup)
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/window.py", line 768, in update
    selected_device_id = _find_selected_device_id()
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/window.py", line 370, in _find_selected_device_id
    model, item = selection.get_selected()
AttributeError: 'NoneType' object has no attribute 'get_selected'
Traceback (most recent call last):
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/__init__.py", line 165, in _status_changed
    window.update(device, need_popup)
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/window.py", line 768, in update
    selected_device_id = _find_selected_device_id()
  File "..../solaar/test/Solaar-867edf8516f6a5a2ec78a99cf2755bd7bcc4e99d/lib/solaar/ui/window.py", line 370, in _find_selected_device_id
    model, item = selection.get_selected()
AttributeError: 'NoneType' object has no attribute 'get_selected'

For people affected by this,  you can still get all the latest changes (including the one related to sleep/wake-up) by using the prior to last tree

https://github.com/pwr/Solaar/tree/dcd1a882505518441b737147ff463a6101e517aa

**Comment by noabody** [comment]
```diff
From 2b08c5e0c90e32bc54b88d7c10d5a2a31943df07 Mon Sep 17 00:00:00 2001
From: Tristin Celestin <tristian.celestin@gmail.com>
Date: Wed, 1 Jan 2014 21:45:44 -0500
Subject: [PATCH] Added border around tree view.

---
 lib/solaar/ui/window.py | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/lib/solaar/ui/window.py b/lib/solaar/ui/window.py
index b56707a..9bf9ec5 100644
--- a/lib/solaar/ui/window.py
+++ b/lib/solaar/ui/window.py
@@ -303,6 +303,11 @@ def _create_window_layout():
 	assert _tree.get_selection().get_mode() == Gtk.SelectionMode.SINGLE
 	_tree.get_selection().connect('changed', _device_selected)
 
+	tree_scroll = Gtk.ScrolledWindow()
+	tree_scroll.add(_tree)
+	tree_scroll.set_min_content_width(_tree.get_size_request()[0])
+	tree_scroll.set_shadow_type(Gtk.ShadowType.IN)
+
 	tree_panel = Gtk.Box.new(Gtk.Orientation.VERTICAL, 0)
 	tree_panel.set_homogeneous(False)
 	tree_panel.pack_start(_tree, True, True, 0)
```
The code seems perfectly innocuous at a glance.  I don't have any background in this programming language, or any for that matter.  Still... I'm guessing there's something like an include or library missing.

**Comment by lopsided98** [comment]
I saw this PR earlier and thought the code looked a little weird because `tree_scroll` is created and then never used, but I didn't think much about it because I have never used Gtk. The issue is that `_tree` is being added to both a `Gtk.ScrolledWindow`, and `tree_panel`, which causes things to break. The fix is to add `tree_scroll` to `tree_panel`, which establishes the correct hierarchy. See #454.

**Comment by noabody** [comment]
And I spent the last four hours almost coming up with the same answer.  It seemed to fit anyway.  Each piece in the hierarchy referencing the one before.though.  New patch works fine.
